export const categories = [
  "Poniedziałek",
  "Wtorek",
  "Środa",
  "Czwartek",
  "Piątek",
  "Sobota",
  "Niedziela",
  "Imieniny",
  "Urodziny",
  "Rocznice",
  "Święta",
  "Walentynki",
  "Dzień Matki",
  "Dzień Ojca",
  "Na dzień dobry",
  "Dobry wieczór",
  "Miłego dnia",
  "Spokojnej nocy",
  "Poranna motywacja",
  "Motywacja",
  "Wdzięczność",
  "Miłość",
  "Przyjaźń",
  "Szczęście",
  "Inspiracja",
  "Gratulacje",
  "Życzenia szybkiego powrotu do zdrowia",
  "Podziękowania",
  "Przeprosiny",
  "Dla mamy",
  "Dla taty",
  "Dla przyjaciółki",
  "Dla kolegi",
  "Dla rodzeństwa",
  "Wiosna",
  "Lato",
  "Jesień",
  "Zima",
];
